language: cpp
matrix:
  include:
  - os: linux
    dist: bionic
  - os: osx
    osx_image: xcode11
  - os: windows
    before_install:
    - choco install make -y
    - choco install zip -y
addons:
  apt:
    packages:
    - git
    - gdb
    - curl
    - cmake
    - libx11-dev
    - libglu1-mesa-dev
    - libxrandr-dev
    - libxinerama-dev
    - libxcursor-dev
    - libxi-dev
    - zlib1g-dev
    - libasound2-dev
    - libgtk2.0-dev
    - libjack-jackd2-dev
    - jq
  homebrew:
    packages:
    - git
    - wget
    - cmake
    - autoconf
    - automake
    - libtool
    - jq
    - python
git:
  submodules: true
env:
  global:
  - MAKEFLAGS="-j 2"
install:
- mkdir -p "${HOME}"/Rack
- pushd "${HOME}"/Rack
- curl -o Rack-SDK.zip https://vcvrack.com/downloads/Rack-SDK-1.1.6.zip
- unzip Rack-SDK.zip
- popd
script:
- export RACK_DIR="${HOME}"/Rack/Rack-SDK
- make dep
- make dist
deploy:
  provider: releases
  api_key:
    secure: nMIGJAoGBAKY1mJtfyxF51Z8XSE4q/kLixEUegc4UGyP0lTH/URfJ3Yg7HzNwOXNg\nxWYtBWg8foI6H71J25iDGFYFA7ihY1GwDDlfd/RmYzBHD3nrVRdzYvvqKZgAfS9J\nvQnqfMVBRNYlP6osvgf394BvOTCrXh7WEQX6zLD0PO1wKgIEHhBzAgMBAAE=
  file_glob: true
  file: dist/IggyLabs-*-*.zip
  skip_cleanup: true
  on:
    repo: isabelgk/IggyLabsModules
    tags: true
